import { Listing, generateDeterministicId } from './index';

/**
 * Seed data: 150+ mock listings across Florida markets (Land O Lakes, Tampa, Orlando, Miami areas)
 * All addresses are masked for privacy.
 * Uses deterministic IDs so same listings always get same IDs.
 */

const SEED_LISTINGS: Listing[] = [
  // Land O Lakes, FL 34639
  {
    id: generateDeterministicId('1234-Land O Lakes-34639-450000'),
    addressMasked: '1234 *** St, Land O Lakes, FL',
    city: 'Land O Lakes',
    state: 'FL',
    zip: '34639',
    price: 450000,
    beds: 3,
    baths: 2,
    sqft: 2000,
    lotSqft: 7500,
    yearBuilt: 2015,
    propertyType: 'SINGLE_FAMILY',
    hoaMonthly: null,
    taxesAnnualEstimate: 5400,
    insuranceAnnualEstimate: 2700,
    lat: 28.15,
    lng: -82.45,
    features: ['garage', 'pool', 'fenced yard'],
    photos: ['/stock/home1.jpg'],
    createdAt: new Date(),
  },
  {
    id: "temp",
    addressMasked: '5678 *** Ln, Land O Lakes, FL',
    city: 'Land O Lakes',
    state: 'FL',
    zip: '34639',
    price: 525000,
    beds: 4,
    baths: 2.5,
    sqft: 2400,
    lotSqft: 8000,
    yearBuilt: 2018,
    propertyType: 'SINGLE_FAMILY',
    hoaMonthly: null,
    taxesAnnualEstimate: 6300,
    insuranceAnnualEstimate: 3150,
    lat: 28.16,
    lng: -82.44,
    features: ['garage', 'large deck', 'smart home'],
    photos: ['/stock/home2.jpg'],
    createdAt: new Date(),
  },
  {
    id: "temp",
    addressMasked: '9012 *** Dr, Land O Lakes, FL',
    city: 'Land O Lakes',
    state: 'FL',
    zip: '34639',
    price: 380000,
    beds: 3,
    baths: 2,
    sqft: 1700,
    lotSqft: 6000,
    yearBuilt: 2010,
    propertyType: 'SINGLE_FAMILY',
    hoaMonthly: null,
    taxesAnnualEstimate: 4560,
    insuranceAnnualEstimate: 2280,
    lat: 28.14,
    lng: -82.46,
    features: ['garage', 'fenced yard'],
    photos: ['/stock/home3.jpg'],
    createdAt: new Date(),
  },
  // Westchase, FL 33626 (Tampa area)
  {
    id: "temp",
    addressMasked: '2345 *** Way, Westchase, FL',
    city: 'Westchase',
    state: 'FL',
    zip: '33626',
    price: 550000,
    beds: 4,
    baths: 3,
    sqft: 2600,
    lotSqft: 6500,
    yearBuilt: 2019,
    propertyType: 'SINGLE_FAMILY',
    hoaMonthly: 150,
    taxesAnnualEstimate: 6600,
    insuranceAnnualEstimate: 3300,
    lat: 28.06,
    lng: -82.62,
    features: ['garage', 'community pool', 'HOA amenities'],
    photos: ['/stock/home4.jpg'],
    createdAt: new Date(),
  },
  {
    id: "temp",
    addressMasked: '6789 *** Court, Westchase, FL',
    city: 'Westchase',
    state: 'FL',
    zip: '33626',
    price: 480000,
    beds: 3,
    baths: 2,
    sqft: 2100,
    lotSqft: null,
    yearBuilt: 2016,
    propertyType: 'TOWNHOME',
    hoaMonthly: 200,
    taxesAnnualEstimate: 5760,
    insuranceAnnualEstimate: 2880,
    lat: 28.05,
    lng: -82.63,
    features: ['garage', 'community amenities'],
    photos: ['/stock/home5.jpg'],
    createdAt: new Date(),
  },
  // Downtown Tampa, FL 33602
  {
    id: "temp",
    addressMasked: '123 *** Ave, Tampa, FL',
    city: 'Tampa',
    state: 'FL',
    zip: '33602',
    price: 380000,
    beds: 2,
    baths: 2,
    sqft: 1200,
    lotSqft: null,
    yearBuilt: 2008,
    propertyType: 'CONDO',
    hoaMonthly: 350,
    taxesAnnualEstimate: 4560,
    insuranceAnnualEstimate: 2280,
    lat: 27.97,
    lng: -82.46,
    features: ['city views', 'fitness center', 'concierge'],
    photos: ['/stock/home6.jpg'],
    createdAt: new Date(),
  },
  {
    id: "temp",
    addressMasked: '456 *** Blvd, Tampa, FL',
    city: 'Tampa',
    state: 'FL',
    zip: '33602',
    price: 420000,
    beds: 3,
    baths: 2,
    sqft: 1500,
    lotSqft: null,
    yearBuilt: 2012,
    propertyType: 'CONDO',
    hoaMonthly: 280,
    taxesAnnualEstimate: 5040,
    insuranceAnnualEstimate: 2520,
    lat: 27.98,
    lng: -82.47,
    features: ['rooftop deck', 'parking', 'gym'],
    photos: ['/stock/home7.jpg'],
    createdAt: new Date(),
  },
  // Carrollwood, FL 33618 (Tampa area)
  {
    id: "temp",
    addressMasked: '789 *** Rd, Carrollwood, FL',
    city: 'Carrollwood',
    state: 'FL',
    zip: '33618',
    price: 510000,
    beds: 4,
    baths: 3,
    sqft: 2350,
    lotSqft: 7200,
    yearBuilt: 2017,
    propertyType: 'SINGLE_FAMILY',
    hoaMonthly: 120,
    taxesAnnualEstimate: 6120,
    insuranceAnnualEstimate: 3060,
    lat: 28.11,
    lng: -82.57,
    features: ['pool', 'garage', 'screened porch'],
    photos: ['/stock/home8.jpg'],
    createdAt: new Date(),
  },
  {
    id: "temp",
    addressMasked: '2468 *** Dr, Carrollwood, FL',
    city: 'Carrollwood',
    state: 'FL',
    zip: '33618',
    price: 440000,
    beds: 3,
    baths: 2,
    sqft: 1950,
    lotSqft: 6800,
    yearBuilt: 2014,
    propertyType: 'SINGLE_FAMILY',
    hoaMonthly: 100,
    taxesAnnualEstimate: 5280,
    insuranceAnnualEstimate: 2640,
    lat: 28.12,
    lng: -82.58,
    features: ['garage', 'patio', 'mature landscaping'],
    photos: ['/stock/home9.jpg'],
    createdAt: new Date(),
  },
  // Winter Park, FL 32789 (Orlando area)
  {
    id: "temp",
    addressMasked: '111 *** Way, Winter Park, FL',
    city: 'Winter Park',
    state: 'FL',
    zip: '32789',
    price: 620000,
    beds: 4,
    baths: 3,
    sqft: 2700,
    lotSqft: 8500,
    yearBuilt: 2016,
    propertyType: 'SINGLE_FAMILY',
    hoaMonthly: null,
    taxesAnnualEstimate: 7440,
    insuranceAnnualEstimate: 3720,
    lat: 28.59,
    lng: -81.35,
    features: ['pool', 'garage', 'guest house'],
    photos: ['/stock/home10.jpg'],
    createdAt: new Date(),
  },
  {
    id: "temp",
    addressMasked: '222 *** Ln, Winter Park, FL',
    city: 'Winter Park',
    state: 'FL',
    zip: '32789',
    price: 550000,
    beds: 3,
    baths: 2,
    sqft: 2100,
    lotSqft: 7000,
    yearBuilt: 2011,
    propertyType: 'SINGLE_FAMILY',
    hoaMonthly: null,
    taxesAnnualEstimate: 6600,
    insuranceAnnualEstimate: 3300,
    lat: 28.58,
    lng: -81.36,
    features: ['pool', 'garage', 'spa'],
    photos: ['/stock/home11.jpg'],
    createdAt: new Date(),
  },
  // Maitland, FL 32751 (Orlando area)
  {
    id: "temp",
    addressMasked: '333 *** Pkwy, Maitland, FL',
    city: 'Maitland',
    state: 'FL',
    zip: '32751',
    price: 420000,
    beds: 3,
    baths: 2,
    sqft: 1800,
    lotSqft: 6000,
    yearBuilt: 2013,
    propertyType: 'SINGLE_FAMILY',
    hoaMonthly: 80,
    taxesAnnualEstimate: 5040,
    insuranceAnnualEstimate: 2520,
    lat: 28.65,
    lng: -81.47,
    features: ['garage', 'fenced yard', 'shed'],
    photos: ['/stock/home12.jpg'],
    createdAt: new Date(),
  },
  {
    id: "temp",
    addressMasked: '444 *** Cir, Maitland, FL',
    city: 'Maitland',
    state: 'FL',
    zip: '32751',
    price: 385000,
    beds: 2,
    baths: 2,
    sqft: 1500,
    lotSqft: null,
    yearBuilt: 2015,
    propertyType: 'CONDO',
    hoaMonthly: 120,
    taxesAnnualEstimate: 4620,
    insuranceAnnualEstimate: 2310,
    lat: 28.64,
    lng: -81.48,
    features: ['pool access', 'fitness center'],
    photos: ['/stock/home13.jpg'],
    createdAt: new Date(),
  },
  // Downtown Orlando, FL 32801
  {
    id: "temp",
    addressMasked: '555 *** St, Orlando, FL',
    city: 'Orlando',
    state: 'FL',
    zip: '32801',
    price: 350000,
    beds: 2,
    baths: 2,
    sqft: 1100,
    lotSqft: null,
    yearBuilt: 2010,
    propertyType: 'CONDO',
    hoaMonthly: 300,
    taxesAnnualEstimate: 4200,
    insuranceAnnualEstimate: 2100,
    lat: 28.54,
    lng: -81.38,
    features: ['downtown living', 'restaurant access'],
    photos: ['/stock/home14.jpg'],
    createdAt: new Date(),
  },
  {
    id: "temp",
    addressMasked: '666 *** Ave, Orlando, FL',
    city: 'Orlando',
    state: 'FL',
    zip: '32801',
    price: 475000,
    beds: 3,
    baths: 2,
    sqft: 1700,
    lotSqft: null,
    yearBuilt: 2014,
    propertyType: 'CONDO',
    hoaMonthly: 250,
    taxesAnnualEstimate: 5700,
    insuranceAnnualEstimate: 2850,
    lat: 28.55,
    lng: -81.37,
    features: ['rooftop pool', 'city views'],
    photos: ['/stock/home15.jpg'],
    createdAt: new Date(),
  },
  // Coral Gables, FL 33134 (Miami area)
  {
    id: "temp",
    addressMasked: '777 *** Pl, Coral Gables, FL',
    city: 'Coral Gables',
    state: 'FL',
    zip: '33134',
    price: 750000,
    beds: 4,
    baths: 3,
    sqft: 3000,
    lotSqft: 9000,
    yearBuilt: 2012,
    propertyType: 'SINGLE_FAMILY',
    hoaMonthly: null,
    taxesAnnualEstimate: 9000,
    insuranceAnnualEstimate: 4500,
    lat: 25.74,
    lng: -80.27,
    features: ['pool', 'garage', 'garden'],
    photos: ['/stock/home16.jpg'],
    createdAt: new Date(),
  },
  {
    id: "temp",
    addressMasked: '888 *** Rd, Coral Gables, FL',
    city: 'Coral Gables',
    state: 'FL',
    zip: '33134',
    price: 650000,
    beds: 3,
    baths: 2,
    sqft: 2400,
    lotSqft: 8000,
    yearBuilt: 2008,
    propertyType: 'SINGLE_FAMILY',
    hoaMonthly: null,
    taxesAnnualEstimate: 7800,
    insuranceAnnualEstimate: 3900,
    lat: 25.75,
    lng: -80.28,
    features: ['pool', 'courtyard'],
    photos: ['/stock/home17.jpg'],
    createdAt: new Date(),
  },
  // Brickell, Miami, FL 33131
  {
    id: "temp",
    addressMasked: '999 *** Tower, Miami, FL',
    city: 'Miami',
    state: 'FL',
    zip: '33131',
    price: 580000,
    beds: 2,
    baths: 2,
    sqft: 1400,
    lotSqft: null,
    yearBuilt: 2015,
    propertyType: 'CONDO',
    hoaMonthly: 400,
    taxesAnnualEstimate: 6960,
    insuranceAnnualEstimate: 3480,
    lat: 25.76,
    lng: -80.19,
    features: ['city views', 'gym', 'concierge'],
    photos: ['/stock/home18.jpg'],
    createdAt: new Date(),
  },
  {
    id: "temp",
    addressMasked: '1111 *** Blvd, Miami, FL',
    city: 'Miami',
    state: 'FL',
    zip: '33131',
    price: 520000,
    beds: 2,
    baths: 2,
    sqft: 1300,
    lotSqft: null,
    yearBuilt: 2013,
    propertyType: 'CONDO',
    hoaMonthly: 350,
    taxesAnnualEstimate: 6240,
    insuranceAnnualEstimate: 3120,
    lat: 25.77,
    lng: -80.20,
    features: ['marina view', 'fitness'],
    photos: ['/stock/home19.jpg'],
    createdAt: new Date(),
  },
];

// Generate more listings to reach 150+
function generateAdditionalListings(): Listing[] {
  const additional: Listing[] = [];
  const zipCodes = [
    { zip: '34639', city: 'Land O Lakes', state: 'FL', lat: 28.15, lng: -82.45 },
    { zip: '33626', city: 'Westchase', state: 'FL', lat: 28.06, lng: -82.62 },
    { zip: '33618', city: 'Carrollwood', state: 'FL', lat: 28.11, lng: -82.57 },
    { zip: '32789', city: 'Winter Park', state: 'FL', lat: 28.59, lng: -81.35 },
    { zip: '32751', city: 'Maitland', state: 'FL', lat: 28.65, lng: -81.47 },
    { zip: '32801', city: 'Orlando', state: 'FL', lat: 28.54, lng: -81.38 },
    { zip: '33134', city: 'Coral Gables', state: 'FL', lat: 25.74, lng: -80.27 },
    { zip: '33131', city: 'Miami', state: 'FL', lat: 25.76, lng: -80.19 },
  ];

  const propertyTypes = ['SINGLE_FAMILY', 'TOWNHOME', 'CONDO'];
  const features = [
    'garage',
    'pool',
    'fenced yard',
    'patio',
    'deck',
    'smart home',
    'fitness center',
    'community pool',
    'HOA amenities',
  ];

  for (let i = SEED_LISTINGS.length; i < 150; i++) {
    const zipInfo = zipCodes[i % zipCodes.length];
    const basePrice = 300000 + Math.random() * 500000;
    const beds = 2 + Math.floor(Math.random() * 3);
    const baths = beds * 0.8 + Math.random() * 0.4;
    const sqft = 1200 + Math.random() * 2500;
    const yearBuilt = 2005 + Math.floor(Math.random() * 20);
    const propertyType = propertyTypes[Math.floor(Math.random() * propertyTypes.length)];
    const hasHOA = Math.random() > 0.6;

    const selectedFeatures = [];
    for (let j = 0; j < Math.floor(Math.random() * 4) + 1; j++) {
      selectedFeatures.push(features[Math.floor(Math.random() * features.length)]);
    }

    additional.push({
      id: "temp",
      addressMasked: `${Math.floor(Math.random() * 9000) + 1000} *** ${['St', 'Ave', 'Ln', 'Dr', 'Rd', 'Way', 'Cir'][Math.floor(Math.random() * 7)]}, ${zipInfo.city}, ${zipInfo.state}`,
      city: zipInfo.city,
      state: zipInfo.state,
      zip: zipInfo.zip,
      price: Math.round(basePrice / 10000) * 10000,
      beds,
      baths: Math.round(baths * 2) / 2,
      sqft: Math.round(sqft / 100) * 100,
      lotSqft: propertyType === 'SINGLE_FAMILY' ? Math.round(5000 + Math.random() * 5000) : null,
      yearBuilt,
      propertyType: propertyType as 'SINGLE_FAMILY' | 'TOWNHOME' | 'CONDO',
      hoaMonthly: hasHOA ? Math.round(50 + Math.random() * 400) : null,
      taxesAnnualEstimate: Math.round((basePrice * 0.012) / 100) * 100,
      insuranceAnnualEstimate: Math.round((basePrice * 0.006) / 100) * 100,
      lat: zipInfo.lat + (Math.random() - 0.5) * 0.1,
      lng: zipInfo.lng + (Math.random() - 0.5) * 0.1,
      features: [...new Set(selectedFeatures)],
      photos: ['/stock/home-generic.jpg'],
      createdAt: new Date(),
    });
  }

  return additional;
}

export const ALL_LISTINGS = [...SEED_LISTINGS, ...generateAdditionalListings()].map((listing, index) => ({
  ...listing,
  id: generateDeterministicId(`listing-${index}-${listing.addressMasked}-${listing.zip}`),
}));
